### ISSUE TITLE
在fatfs 文件系统中， 当xml 文件大小大于1024时 ，执行xml_load会死掉

### ISSUE THREAD

**Issue by ShenxCode** [xfwangqiang/simple_xml#2]
gets接口我尝试了如下修改可正常运行
```
char *local_gets(char *buf, int size, void *file)
{
    FIL *fp = (FIL *)file;
    return f_gets(buf, size, fp);
}
```

**Comment by xfwangqiang** [comment]
关于FatFS，我们的simple_xml应该是不直接支持的，应该是你们自己移植的。由于我没有用FatFS的机会，所以目前我没有办法直接支持FatFS，欢迎贡献你们FatFS的代码。我稍后会把扩展文件系统和内存的方法更新到readme上，感谢

**Comment by ShenxCode** [comment]
抱歉，看错了，应该是我适配的过程中留下的问题，xml_file.c 做的很好，可以很方便的转为其他的文件系统。
